---
name: Server Request
description: Suggest a new game server to be added
title: "[Server Request]: "
labels: ["type: game server request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this game server!
  - type: input
    id: game-server
    attributes:
      label: Game server
      description: What game server would you like to add?
    validations:
      required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
